# Generated by Django 3.1.5 on 2021-02-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'verbose_name': 'Blocked User', 'verbose_name_plural': 'Blocked Users'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterModelOptions(
            name='friendshipmapper',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendship Manager'},
        ),
    ]
